"""create models new

Revision ID: 66cc3d4c3b6c
Revises: cda58c213305
Create Date: 2025-12-06 17:45:53.400658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66cc3d4c3b6c'
down_revision: Union[str, Sequence[str], None] = 'cda58c213305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('ai_tree', sa.Boolean(), nullable=True))
    op.add_column('checkins', sa.Column('ai_real_photo', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_checkins_timestamp'), 'checkins', ['timestamp'], unique=False)
    op.create_index(op.f('ix_task_completion_logs_created_at'), 'task_completion_logs', ['created_at'], unique=False)
    op.add_column('tasks', sa.Column('created_by_user_id', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('assigned_user_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('claimed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_user_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['created_by_user_id'], ['id'])
    op.drop_column('tasks', 'user_id')
    op.add_column('trees', sa.Column('centroid_lat', sa.Float(), nullable=True))
    op.add_column('trees', sa.Column('centroid_lon', sa.Float(), nullable=True))
    op.add_column('trees', sa.Column('segments', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_trees_centroid_lat'), 'trees', ['centroid_lat'], unique=False)
    op.create_index(op.f('ix_trees_centroid_lon'), 'trees', ['centroid_lon'], unique=False)
    op.create_index(op.f('ix_trees_status'), 'trees', ['status'], unique=False)
    op.drop_column('trees', 'successful_waterings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trees', sa.Column('successful_waterings', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_trees_status'), table_name='trees')
    op.drop_index(op.f('ix_trees_centroid_lon'), table_name='trees')
    op.drop_index(op.f('ix_trees_centroid_lat'), table_name='trees')
    op.drop_column('trees', 'segments')
    op.drop_column('trees', 'centroid_lon')
    op.drop_column('trees', 'centroid_lat')
    op.add_column('tasks', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_column('tasks', 'claimed_at')
    op.drop_column('tasks', 'assigned_user_id')
    op.drop_column('tasks', 'created_by_user_id')
    op.drop_index(op.f('ix_task_completion_logs_created_at'), table_name='task_completion_logs')
    op.drop_index(op.f('ix_checkins_timestamp'), table_name='checkins')
    op.drop_column('checkins', 'ai_real_photo')
    op.drop_column('checkins', 'ai_tree')
    # ### end Alembic commands ###
